### ISSUE TITLE
tsygTrace example not working

### ISSUE THREAD

**Issue by mariayanovskaya** [vtsuperdarn/davitpy#332] opened 2018-01-10 08:52 UTC
Hi all, 

Trying to do "the porcelain way" example in the models.ipynb on OSX Sierra. I've run into a few issues.

In  davitpy/davitpy/models/tsyganenko/__init__.py lines 349-357, the code will always fail with the error ```TypeError: slice indices must be integers or None or have an __index__ method```

Also, I am using the already corrected version of __init__.py by @RichardoC. 

Anyone have any ideas how to fix this?

Thanks

**Comment by asreimer** [comment] 2018-01-25 20:57
This really sounds like a `numpy` version issue. 

What is your `numpy` version? If you downgrade to 1.8, this issue will likely go away. It's caused by sloppy indexing, where we don't make sure that the variables used to index a `numpy` array are integers.

The temporary fix is to downgrade numpy. The proper fix is to ensure variables used to index the `numpy` arrays are integers.

**Comment by mariayanovskaya** [comment] 2018-10-16 16:21
Currently, the installation script automatically updates all the modules, including numpy. 

Maybe update the installation files such that the correct version of numpy is installed?

**Comment by ksterne** [comment] 2020-05-08 16:02
It sounds like this is related to #316 and #358, so closing this issue because of that and because this repo is being deprecated.

**Closed by ksterne** 2020-05-08 16:02 UTC
Labels: bug
