### ISSUE TITLE
Installing master branch (0.4) from previous version, package issue

### ISSUE THREAD

**Issue by ksterne** [vtsuperdarn/davitpy#184] opened 2015-11-12 20:48 UTC
So, I was transitioning our main davitpy code for the VT lab and I ran into an issue where upon running the `sudo python setup.py install` , I got the following error:

error: package directory 'gme' does not exist

as it was looking for a ~/davitpy/gme/ directory instead of ~/davitpy/davitpy/gme/.  It seems as though somewhere something got locked so that it wasn't transitioning to the new file structure, even though I blew away the repository and started from new (even deleting the /usr/local/lib/python2.7/dist-packages/davitpy* directories).  It seems as though the part of the code filling up the sources list wasn't adding davitpy to the beginning of the packages as it should, for example: davitpy.models, davitpy.models.iri .

So, two ways around this for this error.  The first is specific to this problem and would break everything else.  After the sources list I added:

    sources = [ 'davitpy.' + s for s in sources ]

which added the davitpy to everything and seems to get things working.  

The other one here, which is maybe more of an enhancement and could work for everyone.  Someone looked at that part of the code and wondered if it was even necessary.  If you import find_packages from setuptools and then change the line in the big setup call to:

    packages=find_packages(),

then populating the sources list isn't necessary.  I think the only caveat is that the find_packages() only works if there is an `__init__.py` file is in each package that you want to install.  Does anyone else have any experience with this and why we would want to use the nested for loops to populate a list of packages that we want to sent to setup?  Maybe this is something we can add to the next release.

**Comment by asreimer** [comment] 2015-11-12 21:44
Interesting. I think it is __very__ weird that suddenly now there are problems with installing davitpy even though nothing has changed in how the sources files are being added (since the last master+setup release). The weirdness factor is increased when you consider that none of us ever ran in to any install issues like this (that were reported at least) while developing this code in the develop branch... @ksterne is this an issue you run in to for just the current master branch or also the develop branch?

What do you mean by:
>as it was looking for a ~/davitpy/gme/ directory instead of ~/davitpy/davitpy/gme/.
what was looking for `~/davitpy/gme/`? and how do you know it was? Is this on Ubuntu or a different OS?

One thing to test is this:
1) Navigate to the directory in which you have the davitpy repository (for me this is /home/ashtonsethreimer/davitpy for example)
2) Fire up a python session and run the following:

    import os
    pwd = os.getcwd()
    sources = []
    source_dirs = ['davitpy']
    for s in source_dirs:
        for root, dirs, files in os.walk(pwd+'/'+s):
            if '__init__.py' in files:
                sources.append('.'.join(
                    root.replace(pwd,'').strip('/').split('/')
                    ))
    print sources

This code may look familiar as it is the piece of the code that populates the sources list used to install davitpy. You should get the following output:

>['davitpy', 'davitpy.gme', 'davitpy.gme.isr', 'davitpy.gme.ind', 'davitpy.gme.base', 'davitpy.gme.sat', 'davitpy.gme.plotting', 'davitpy.models', 'davitpy.models.msis', 'davitpy.models.raydarn', 'davitpy.models.tsyganenko', 'davitpy.models.aacgm', 'davitpy.models.igrf', 'davitpy.models.hwm', 'davitpy.models.iri', 'davitpy.utils', 'davitpy.pydarn', 'davitpy.pydarn.dmapio', 'davitpy.pydarn.radar', 'davitpy.pydarn.sdio', 'davitpy.pydarn.plotting', 'davitpy.pydarn.proc', 'davitpy.pydarn.proc.signal', 'davitpy.pydarn.proc.music', 'davitpy.pydarn.proc.fov']

This output is also seen at the end of any `python setup.py install` command. If you don't see this output then there is more likely a some problem on your end, and not necessarily with the davitpy code. Is there any other information you can provide to help me reproduce the error you are getting? So far, I can't.

This all being said, if there's a better way of populating the packages list, I'm all for that so long as it doesn't break things of course. It would be great if we could figure out what exactly is going on here though.

**Comment by ksterne** [comment] 2015-11-12 22:19
So, a little bit of back story for completeness and to answer your questions.

I agree this is pretty weird since the setup.py has been out for a while, but this is the first I'm doing it on this computer as this is our "always works" code set so I usually keep it on the master.  Though I have switched over the develop from time to time, but didn't notice a problem.  I ran into this when transitioning to the 0.4 release.  Same thing happens on the current develop branch.

I know it was looking for ~/davitpy/gme/ since when I saw the error I created this directory and then the error was something like "cannot find ~/davitpy/gme/__init__.py".  This is on Ubuntu 12.

Here's the output of sources (here the davitpy install is on the root directory, /davitpy):

['', 'gme', 'gme.ind', 'gme.plotting', 'gme.sat', 'gme.isr', 'gme.base', 'utils', 'pydarn', 'pydarn.sdio', 'pydarn.plotting', 'pydarn.proc', 'pydarn.proc.signal', 'pydarn.proc.music', 'pydarn.radar', 'pydarn.dmapio', 'models', 'models.msis', 'models.raydarn', 'models.igrf', 'models.hwm', 'models.iri', 'models.tsyganenko', 'models.aacgm']

I also get the warning of:

WARNING: '' not a valid package name; please use only.-separated package names in setup.py

which makes sense since it's not populating the 'davitpy' name and the first item in the list is just ''.  

The only thing I can think of why I'm running into it and no one else probably has is that I'm installing this on the root directory.  When I moved the old repository to a backup (I did this after getting the same issue when I pulled the 0.4 master down, figured to start semi-fresh) , I had to clone the new repository as root, but then did a `chown -R user:user davitpy/` to change the permissions so that I could work within it.   I'm working if there's something odd going on with being on the root directory.

I've started up a branch that makes use of the `find_packages()` functions.  You can read more about this function at:  https://pythonhosted.org/setuptools/setuptools.html#using-find-packages .
It seems to add a little bit more options here if there was ever a package we would want to exclude from the setup process.

**Comment by asreimer** [comment] 2015-11-12 23:31
Yup, this is a bug. A bit obscure and only caused by one specific usage case: installing davitpy from the repo files after they have been cloned to the root directory of a linux machine. A trick-sy one! :)

First of all the error you get when you create that gme directory is one that you caused yourself by creating that gme directory. It happens because the code that makes the sources list is checking that directory (it checks every directory within the davitpy directory) for `__init__.py` files. Since you created that gme directory and there's no `__init__.py` file in it, you get the error.

Your sources list on the other hand, points to the source of the problem. Comparing yours with the one I posted, everything is missing `davitpy` in front of it. This is an edge-case when this error will manifest because you cloned the davitpy repository to `/` on your machine. In reference to the loop I posted above, what happens is:
1) `pwd = '/davitpy/'`
2) the line of code in the sources loop that contains `root.replace(pwd,'')` removes all occurrences of pwd. Each `root ` in the loop contains `/davitpy/davitpy` in it so __both__ get stripped out, hence the sources list that you posted and the failure of the installation.

This bug only shows it's ugly head if you have the repo source installed in root (`/`) or in a directory like this: `/davitpy/davitpy/davitpy`. Weird haha.

Two options to fix this:
1) Add `from setuptools import find_packages()` to the top of the setup.py file and replace [these lines of code](https://github.com/vtsuperdarn/davitpy/blob/master/setup.py#L71-L79) with `sources = find_packages()` (I like this solution the best)
2) change [this line of code](https://github.com/vtsuperdarn/davitpy/blob/master/setup.py#L78) to this:
`root.replace(pwd,'',max=1).strip('/').split('/')`

Nice find on the `find_packages()` method. And nice bug find too. That one has been there for years!

**Comment by cmeeren** [comment] 2015-11-13 07:24
Potentially relevant: [this post](http://blog.ionelmc.ro/2014/05/25/python-packaging/) and [this post](http://blog.ionelmc.ro/2014/06/25/python-packaging-pitfalls/) and references therein.

**Comment by MuhammadVT** [comment] 2015-11-13 13:35
Hey Ashton,

using *find_packages() * seems to be the one that prevents other edge-cases
to show up. If the second option is used, then shouldn't it be
*root.replace(pwd,'',1).strip('/').split('/')*  as there is no *max*
argument in *replace* function?

Thanks.

**Comment by asreimer** [comment] 2015-11-16 21:30
@MuhammadVT,

You are correct, replace(pwd,'',1) is the correct syntax.

**Comment by asreimer** [comment] 2015-12-03 20:00
This is fixed by #190.

**Closed by asreimer** 2015-12-03 20:00 UTC
Labels: bug, enhancement
