### ISSUE TITLE
TypeError on input

### ISSUE THREAD

**Issue by heinet** [vtsuperdarn/davitpy#238] opened 2016-04-19 17:16 UTC
When I try to input davitpy, I get the following error.  This occurs even when I try to import the GOES notebook.

Populating the interactive namespace from numpy and matplotlib
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-7aca422ea469> in <module>()
      3 from matplotlib import pyplot as plt
      4 import datetime
----> 5 from davitpy import gme #This is the DavitPy GeoMagnetic Environment module

/Users/heinet/Library/Python/2.7/lib/python/site-packages/davitpy-0.5-py2.7-macosx-10.6-x86_64.egg/davitpy/__init__.pyc in <module>()
    616     from davitpy import pydarn
    617 except Exception, e:
--> 618     logging.exception('problem importing pydarn: ' + e)
    619 
    620 try:

TypeError: coercing to Unicode: need string or buffer, exceptions.TypeError found

In [2]:

**Comment by spacecataz** [comment] 2016-04-19 17:19
Can confirm on pure macports install.

**Comment by asreimer** [comment] 2016-04-19 18:28
I cannot reproduce this problem on the OpenSUSE nor Fedora.

I'm guessing there is some problem with your mac installation of davitpy. Likely, something is wrong in the pydarn module judging from the error message you have included: "618 logging.exception('problem importing pydarn: ' + e)"

In a python shell, what do you get if you run:
`from davitpy import pydarn` ?

**Comment by Shirling-VT** [comment] 2016-04-19 19:36
Hi all,

I just installed davitpy in my macbook though the mac_brew dependencies,
though almost manually after failing on several packages installation. But
it seems to work well here without the issue heinet mentioned. I also
suspect something was wrong during the installation. You have to be very
carefully when doing the dependencies installation and make sure every
required packages are installed successfully before you do the real
installation.

On Tue, Apr 19, 2016 at 2:28 PM, Ashton Reimer <notifications@github.com>
wrote:

> I cannot reproduce this problem on the OpenSUSE nor Fedora.
>
> I'm guessing there is some problem with your mac installation of davitpy.
> Likely, something is wrong in the pydarn module judging from the error
> message you have included: "618 logging.exception('problem importing
> pydarn: ' + e)"
>
> In a python shell, what do you get if you run:
> from davitpy import pydarn ?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/vtsuperdarn/davitpy/issues/238#issuecomment-212057791>
>



-- 
Best wishes,
Xueling

**Comment by spacecataz** [comment] 2016-04-20 15:53
Importing pydarn yields the exact same error in the exact same file.
I ran the python_install_mac_port.sh script, and it executes successfully.  However, it is installing all of these libraries into the OS X version of Python (/usr/bin/python) instead of the Macports version.  This is because the script installs PIP not via macports, but via easy_install.  Therefore, all of the libraries are installed in the wrong spot.  If PIP is installed via macports and properly selected, installation of dependencies works flawlessly and the library installs correctly.

Via this conversation, there are several issues here:
1) The dependency install script for macports is simply wrong.  Including the following lines installs PIP for the macports installation of Python and fixes the script: 
` sudo port install py27-pip
  sudo port install pip_select
  sudo port select --set pip pip27
`
2) The install scripts for macintosh are, as previously pointed out, "suggestions and not rules".  Just running the install scripts is unlikely to succeed (as Shirling-VT pointed out above).  Perhaps it is time to update the documentation to reflect this.

3) There is no dependency checking in the install script, which would decrease the time to pinpoint an issue.

Additionally, it appears that the developers are not willing to run MacPorts themselves.  Everyone attempted to reproduce the error on other systems and other install approaches, which is not helpful.  From other threads, it appears that MacPorts is not held in high regard by the development team.  In isolation, this is fine.  However, it is incongruous with the documentation and install scripts, which give the appearance of real support for a MacPorts installation.  Perhaps removing this material should be considered.

**Comment by asreimer** [comment] 2016-04-20 16:18
Hi @spacecataz 

As you have pointed out, there is a problem with the dependency script. Since none of the current developers have Mac computers (that I'm aware of), we haven't been able to do any testing/bugfixes/improvements to the dependency install scripts for OS X.

If you could make a pull request with a working macports dependency script, it would be much appreciated. Problem is that this dependency script seems to be OS X version based too. The homebrew and macports scripts USED to work but at OS X updated, they don't anymore. Also, if you have suggestions on where to update the documentation that would be great too. We do state that the only active development is on Linux in the install instructions, but clearly that is a bit lacking.

We are all volunteering our time to develop this code and none of the current developers own macbooks (again, as far as I know). And while people have had trouble installing the dependencies in the past, they have either sorted it out themselves and not reported back here, or they have simply run davitpy in a linux VM. 

I would love to get the dependency thing resolved, but not owning a macbook makes that kind of hard for me to work on :/

**Comment by Shirling-VT** [comment] 2016-04-20 18:33
Hi all,

Xueling here, a graduate student in the SuperDARN research group at
Virginia Tech. I'm more a user on davitpy, and of course far from a
developer. I just got a Macbook and will be glad to help with the mac
dependencies installation issue.

I tried to install davitpy through python_install_mac_port.sh script a
month ago on my friend's macbook and met exactly the same problem as spacecataz
pointed out. As some macbook has its default python installed in it, like
python3.4, but davitpy uses python2.7, therefore the easy_install pip will
become a problem for the following other packages installed through pip. One
other user I know in UCB cannot install davitpy in her macbook properly as
well, though I'm not sure if she met the same problem.  Another obvious
error in our homebrew installation script is that we miss "cd basemap"
command between "git clone hhttps://github.com/matplotlib/basemap.git" and
the last command. Therefore, if a user just runs this script, he or she
won't install basemap correctly and will result in error message when they
try to import basemap. All I want to say is that as some of you mentioned,
we need to update the mac version script.

In fact, not only there will be problem with the mac OS X updates, but also
with Ubuntu OS or some packages update. I just installed davitpy in my lab
computer in Ubuntu 14.04 and cannot install basemap correctly through the
debian_dependencies.sh script. Finally, I installed basemap from the source
and everything is working again. Maybe we should draw people's attention by
writing something like this:"Please make sure every dependency is
installed successfully before you do the actual davitpy installation! If
there's any error message during the dependencies installation, please
reinstall specific dependency manually! Or your davitpy might not work." in
our installation instructions.

Best wishes,
Xueling



On Wed, Apr 20, 2016 at 12:18 PM, Ashton Reimer <notifications@github.com>
wrote:

> Hi @spacecataz <https://github.com/spacecataz>
>
> As you have pointed out, there is a problem with the dependency script.
> Since none of the current developers have Mac computers (that I'm aware
> of), we haven't been able to do any testing/bugfixes/improvements to the
> dependency install scripts for OS X.
>
> If you could make a pull request with a working macports dependency
> script, it would be much appreciated. Problem is that this dependency
> script seems to be OS X version based too. The homebrew and macports
> scripts USED to work but at OS X updated, they don't anymore. Also, if you
> have suggestions on where to update the documentation that would be great
> too. We do state that the only active development is on Linux in the
> install instructions, but clearly that is a bit lacking.
>
> We are all volunteering our time to develop this code and none of the
> current developers own macbooks (again, as far as I know). And while people
> have had trouble installing the dependencies in the past, they have either
> sorted it out themselves and not reported back here, or they have simply
> run davitpy in a linux VM.
>
> I would love to get the dependency thing resolved, but not owning a
> macbook makes that kind of hard for me to work on :/
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/vtsuperdarn/davitpy/issues/238#issuecomment-212498172>
>



-- 
Best wishes,
Xueling

**Comment by asreimer** [comment] 2016-05-05 17:48
Fixed in #246

**Closed by asreimer** 2016-05-05 17:48 UTC
